version: "2.4"
services:
  web:
    image: flask_app
    mem_limit: 700mb
    restart: "unless-stopped"
    stop_signal: SIGINT
    ports:
      - "33000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "app"
    ports:
      - 5432:5432
    # volumes:
    #   - ./docker_data/init.sql:/docker-entrypoint-initdb.d/init.sql
